name: OddType
favicon: null
layout_spectrum: 0.91326
typography_spectrum: 0.65588
title: Odd Type
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6b004f'
    - '#e3a448'
    - '#b14e25'
    - '#000000'
    - '#ff0000'
  brandStrength: 0.8125
  lightness: 0.875
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
