name: OddType
favicon: null
layout_spectrum: 0.15514979674480855
typography_spectrum: 0.8716198054607958
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.019361548824235797
  lightness: 0.7916747201234102
  saturation: 0.22333394829183817
  rhythmicContrast: 0.08665148005820811
purpose: []
