name: OddType
favicon: null
layout_spectrum: 0.15514979674480855
typography_spectrum: 0.8716198054607958
title: Odd Type
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6b004f'
    - '#e3a448'
    - '#b14e25'
    - '#000000'
    - '#ff0000'
  brandStrength: 0.019361548824235797
  lightness: 0.7916747201234102
  saturation: 0.22333394829183817
  rhythmicContrast: 0.08665148005820811
purpose: []
